version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: b2b-saas-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: b2b_saas_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d b2b_saas_demo"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data: 